/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example
import org.example.PrimeNumber
import org.example.EvenNumber
import org.example.OddNumber
import org.example.ValidateNumber

fun main() {
    try{
        // println("Ingrese un numero")
        // val input = readLine()?.toInt() ?: throw IllegalArgumentException("Entrada NO valida")
        val input = 100
        val validator = ValidateNumber()
        validator.numberClassification(input)

    }catch (e: Exception) {
        println("Error: ${e.message}")
    }
}
